### ISSUE TITLE
Lable the cables

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#31] opened 2016-03-08 21:01 UTC
Everything we need to use during the conference needs to be labeled

**Comment by abrolag** [comment] 2016-03-15 19:32
So is there a cable label table?
Sorry, couldn't resit.
Ah, my coat. Thanks :)

**Comment by dvzrv** [comment] 2016-03-15 20:29
http://www.kira-fansub.com/wp-content/uploads/2012/03/ba-dum-tss1.jpg
;-)

**Comment by dvzrv** [comment] 2016-04-05 09:09
closing for being a duplicate of #32

**Closed as completed by dvzrv** 2016-04-05 09:09 UTC
